version: '2.4'
services:
  mysql:
    container_name: mysql-all
    restart: always
    image: mysql:latest
    volumes:
      - ${VOLUME_DIR}/module/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test
    networks:
      - jp-network

  fastapi:
    container_name: fastapi-all
    restart: always
    image: fastapi:latest
    volumes:
      - ${VOLUME_DIR}/appData/thumb:/home/minerva/appData/thumb
    cpu_count: 1
    cpu_shares: 2048
    ports:
      - "8000:8000"
    networks:
      - jp-network

  app:
    container_name: minerva-all
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - fastapi
    networks:
      - jp-network

networks:
  jp-network:
    driver: bridge
