version: '2.4'
services:
  mysql:
    container_name: mysql-test
    restart: always
    image: mysql:latest
    volumes:
      - ${VOLUME_DIR}/module/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test
    networks:
      - jp-network

  app:
    container_name: app-test
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    networks:
      - jp-network

networks:
  jp-network:
    driver: bridge
